package com.tuodao.bp.sms.db.mapper;

import com.tuodao.bp.sms.db.model.SmsAccout;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

@Mapper
public interface SmsAccoutMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_accout
     *
     * @mbg.generated
     */
    @Select({
            "select",
            "id, sms_servicer, sms_account, sms_password,sms_url, sms_status",
            "from sms_accout",
            "where sms_status = 1  order by gmt_modify desc"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "sms_servicer", property = "smsServicer", jdbcType = JdbcType.INTEGER),
            @Result(column = "sms_account", property = "smsAccount", jdbcType = JdbcType.VARCHAR),
            @Result(column = "sms_password", property = "smsPassword", jdbcType = JdbcType.VARCHAR),
            @Result(column = "sms_url", property = "smsUrl", jdbcType = JdbcType.VARCHAR),
            @Result(column = "sms_status", property = "smsStatus", jdbcType = JdbcType.INTEGER)
    })
    List<SmsAccout> selectBySmsType();

}