package com.tuodao.bp.sms.db.model;

public class SmsAccout {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_accout.id
     *
     * @mbg.generated
     */
    private Long id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_accout.sms_servicer
     *
     * @mbg.generated
     */
    private Integer smsServicer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_accout.sms_account
     *
     * @mbg.generated
     */
    private String smsAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_accout.sms_password
     *
     * @mbg.generated
     */
    private String smsPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_accout.sms_type
     *
     * @mbg.generated
     */
    private String smsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_accout.sms_url
     *
     * @mbg.generated
     */
    private String smsUrl;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_accout.sms_status
     *
     * @mbg.generated
     */
    private Integer smsStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_accout.id
     *
     * @return the value of sms_accout.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_accout.id
     *
     * @param id the value for sms_accout.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_accout.sms_type
     *
     * @return the value of sms_accout.sms_type
     * @mbg.generated
     */
    public String getSmsType() {
        return smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_accout.sms_type
     *
     * @param smsType the value for sms_accout.sms_type
     * @mbg.generated
     */
    public void setSmsType(String smsType) {
        this.smsType = smsType == null ? null : smsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_accout.sms_account
     *
     * @return the value of sms_accout.sms_account
     * @mbg.generated
     */
    public String getSmsAccount() {
        return smsAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_accout.sms_account
     *
     * @param smsAccount the value for sms_accout.sms_account
     * @mbg.generated
     */
    public void setSmsAccount(String smsAccount) {
        this.smsAccount = smsAccount == null ? null : smsAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_accout.sms_password
     *
     * @return the value of sms_accout.sms_password
     * @mbg.generated
     */
    public String getSmsPassword() {
        return smsPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_accout.sms_password
     *
     * @param smsPassword the value for sms_accout.sms_password
     * @mbg.generated
     */
    public void setSmsPassword(String smsPassword) {
        this.smsPassword = smsPassword == null ? null : smsPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_accout.sms_url
     *
     * @return the value of sms_accout.sms_url
     * @mbg.generated
     */
    public String getSmsUrl() {
        return smsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_accout.sms_url
     *
     * @param smsUrl the value for sms_accout.sms_url
     * @mbg.generated
     */
    public void setSmsUrl(String smsUrl) {
        this.smsUrl = smsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_accout.sms_status
     *
     * @return the value of sms_accout.sms_status
     * @mbg.generated
     */
    public Integer getSmsStatus() {
        return smsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_accout.sms_status
     *
     * @param smsStatus the value for sms_accout.sms_status
     * @mbg.generated
     */
    public void setSmsStatus(Integer smsStatus) {
        this.smsStatus = smsStatus;
    }

    public Integer getSmsServicer() {
        return smsServicer;
    }

    public void setSmsServicer(Integer smsServicer) {
        this.smsServicer = smsServicer;
    }
}