package com.tuodao.bp.sms.db.model;

import java.util.Date;

public class SmsLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.request_id
     *
     * @mbg.generated
     */
    private String requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.request_time
     *
     * @mbg.generated
     */
    private Date requestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.sms_servicer
     *
     * @mbg.generated
     */
    private Integer smsServicer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.customs_ip
     *
     * @mbg.generated
     */
    private String customsIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.respose_time
     *
     * @mbg.generated
     */
    private Date resposeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.respose_content
     *
     * @mbg.generated
     */
    private String resposeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_log.respose_result
     *
     * @mbg.generated
     */
    private String resposeResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.id
     *
     * @return the value of sms_log.id
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.id
     *
     * @param id the value for sms_log.id
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.request_id
     *
     * @return the value of sms_log.request_id
     * @mbg.generated
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.request_id
     *
     * @param requestId the value for sms_log.request_id
     * @mbg.generated
     */
    public void setRequestId(String requestId) {
        this.requestId = requestId == null ? null : requestId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.request_time
     *
     * @return the value of sms_log.request_time
     * @mbg.generated
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.request_time
     *
     * @param requestTime the value for sms_log.request_time
     * @mbg.generated
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.mobile
     *
     * @return the value of sms_log.mobile
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.mobile
     *
     * @param mobile the value for sms_log.mobile
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.content
     *
     * @return the value of sms_log.content
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.content
     *
     * @param content the value for sms_log.content
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.customs_ip
     *
     * @return the value of sms_log.customs_ip
     * @mbg.generated
     */
    public String getCustomsIp() {
        return customsIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.customs_ip
     *
     * @param customsIp the value for sms_log.customs_ip
     * @mbg.generated
     */
    public void setCustomsIp(String customsIp) {
        this.customsIp = customsIp == null ? null : customsIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.respose_time
     *
     * @return the value of sms_log.respose_time
     * @mbg.generated
     */
    public Date getResposeTime() {
        return resposeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.respose_time
     *
     * @param resposeTime the value for sms_log.respose_time
     * @mbg.generated
     */
    public void setResposeTime(Date resposeTime) {
        this.resposeTime = resposeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_log.respose_content
     *
     * @return the value of sms_log.respose_code
     * @mbg.generated
     */
    public String getResposeContent() {
        return resposeContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_log.respose_content
     *
     * @param resposeContent the value for sms_log.respose_content
     * @mbg.generated
     */
    public void setResposeContent(String resposeContent) {
        this.resposeContent = resposeContent == null ? null : resposeContent.trim();
    }

    public String getResposeResult() {
        return resposeResult;
    }

    public void setResposeResult(String resposeResult) {
        this.resposeResult = resposeResult;
    }

    public Integer getSmsServicer() {
        return smsServicer;
    }

    public void setSmsServicer(Integer smsServicer) {
        this.smsServicer = smsServicer;
    }

    public SmsLog() {
    }


    public SmsLog(String requestId, Date requestTime, Integer smsServicer, String mobile, String content, String customsIp) {
        this.requestId = requestId;
        this.requestTime = requestTime;
        this.smsServicer = smsServicer;
        this.mobile = mobile;
        this.content = content;
        this.customsIp = customsIp;
    }
}